apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Adityacom7/onprem-secure-ai-platform
    targetRevision: master
    path: apps/ai-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
